version: '3.8'
services:
  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - service
    environment:
      - STAT_SERVER_URL=http://server:9090

  service:
    build: ./ewm-stats/service
    image: ewm-stats
    container_name: ewm-stats
    ports:
      - "9090:9090"
    depends_on:
      - db-stats
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-stats:5432/service
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root

  db-stats:
    image: postgres:13.7-alpine
    container_name: db-stats
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root