version: '3.8'
services:
  db-stats:
    image: postgres:15.1-alpine
    container_name: db-stats
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-db:
      image: postgres:15.1-alpine
      container_name: ewm-service-db
      ports:
        - "6542:5432"
      environment:
        - POSTGRES_DB=ewm
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

  stats-service:
    build: ewm-stats/stats-service
    image: ewm-stats-service
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - db-stats
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-stats:5432/stats
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root


  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVICES_STATSSERVICE_URL=http://stats-service:9090
      - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests


